[book]
authors = ["santyarellano"]
language = "en"
multilingual = false
src = "src"
title = "FRUG Documentation (for v0.1.0)"

[output.html]
git-repository-url = "https://github.com/santyarellano/frug"